### ISSUE TITLE
カロリーから住居を提案する

### ISSUE THREAD

**Issue by calmery** [jphacks/FK_1801#20]

**Comment by calmery** [comment]
高カロリー地域に住みたい！

**Comment by naoyasugita** [comment]
【LIFULLのAPI】
http://developer.homes.co.jp/api/howto

トークン取得用URI:　https://auth.homes.co.jp/token
利用可能APIサーバー:　https://api.homes.co.jp/
ClientID:　YjE0YzU2MmNiOTk2MzI4ZjkzMzcwM2ZkNjEzMGU2
ClientSecret:　利用希望の旨をいただければお伝えします。
